### PR TITLE
Add --non-interactive options to letsencrypt-auto command

### PR DESCRIPTION
**Pull request by dexbleeker**
Fixes issue mentioned here: https://github.com/certbot/certbot/issues/1154

### CODE REVIEW

**Comment by ohemorange** [comment]
The `--text` command no longer has any effect as of #3665, which will be released in Certbot 0.10.0.

**Comment by dexbleeker** [comment]
Removed the flag.

**Comment by iggy** [comment]
does `--non-interactive` break older versions or do they just ignore it?

**Comment by aboe76** [comment]
@dexbleeker and @iggy could you take a look at #30 I think these are the same issues

**Pull request merged**
