### PR TITLE
adds git as dependency

### PR DESCRIPTION
**Pull request by fortunejuggle**
unfortunately letsencrypt clone fails, if pkg git does not exist.
In my opinion it would be usefull to install git bevor installing letsencrypt

### CODE REVIEW

**Comment by wwentland** [comment]
I would recommend to depend on the https://github.com/saltstack-formulas/git-formula, as it already handles differences in package names between platforms. It would be a bit of work to maintain this here also.

See https://github.com/saltstack-formulas/git-formula/blob/master/git/map.jinja for details

**Comment by jochumdev** [comment]
I would just create a state/role with the following contents:

```
#!jinja|yaml
# vi: set ft=yaml.jinja :

include:
  - git
  - letsencrypt
```

This way you can include roles.letsencrypt for example and this formula needs no dependencies.

**Comment by fortunejuggle** [comment]
yes , you are right.But the formular should be self-contained and if git was used it must be installed. 
Better would be gone to make configurable whether git is installed or not, because in most cases you do not need certain version of git

**Comment by fortunejuggle** [comment]
I close this one and create a new pull request.

**Pull request closed without merging**
