### PR TITLE
Fix #17 where install prompts for standalone.

### LINKED ISSUE #17: Certonly install fails because of argument placement
```
----------
          ID: create-initial-cert-www-my.domain.com
    Function: cmd.run
        Name: /opt/letsencrypt/letsencrypt-auto -d my.domain.com certonly
      Result: False
     Comment: Command "/opt/letsencrypt/letsencrypt-auto -d my.domain.com certonly" run
     Started: 14:02:52.437152
    Duration: 1165.16 ms
     Changes:  
```

Because of the positioning of the domain name before certonly.

This command succeeds without error:
`/root/.local/share/letsencrypt/bin/letsencrypt certonly --standalone -d my.domain.com`

### PR DESCRIPTION
**Pull request by benhosmer**

### CODE REVIEW

**Comment by lgunsch** [comment]
The `--standalone` flag should be able to go into the config file, rather than always present on the CLI as an argument. Otherwise this will break for users who use the webroot authenticator, instead of the standalone authenticator.

**Comment by benhosmer** [comment]
@lgunsch You mean here: https://github.com/saltstack-formulas/letsencrypt-formula/blob/master/pillar.example#L5 in the pillar settings using standalone?

```
....
   email = webmaster@example.com
    authenticator = standalone
    webroot-path = /var/lib/www
...
```

**Comment by lgunsch** [comment]
Yes, that is what I meant. You can change the authenticator, and remove unneeded settings like webroot-path.

**Comment by benhosmer** [comment]
Thanks for the clarification @lgunsch

**Pull request closed without merging**
