### PR TITLE
refactor: Use domains' setname as --cert-name option

### PR DESCRIPTION
**Pull request by kiniou**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [X] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes. 
The setname was not used before and the certificate path will not be the same.
The most obvious change that needs to be done is changing the pillar to match the first domain in a domain sets like the following:
```yaml
letsencrypt:
  domains:
    foo.example.com:
      - foo.example.com
```

### Describe the changes you're proposing

Certbot has the ability to name a certificate with the --cert-name option.

This allows us for instance to refers to this same setname to other
configuration and then further automate virtualhost creation in nginx or apache.

### Pillar / config required to test the proposed changes

Here is an example that should write the certificates into `/etc/letsencrypt/live/foo/` path:
```yaml
letsencrypt:
  domains:
    foo:
      - foo.example.com
```
You might need to change the `.example.com` with something real if tested against a real ACME server (I've tested this change locally with a local [pebble server](https://github.com/letsencrypt/pebble)).

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
> ### Does this PR introduce a `BREAKING CHANGE`?
> 
> Yes.
> The setname was not used before and the certificate path will not be the same.
> The most obvious change that needs to be done is changing the pillar to match the first domain in a domain sets like the following:
> 
> ```yaml
> letsencrypt:
>   domains:
>     foo.example.com:
>       - foo.example.com
> ```

@kiniou Thanks for this PR.  Hopefully, @javierbertoli will get a chance to review it soon.  Don't worry about this just yet but if this PR is approved, we would require the commit to be amended so that the breaking change is applied by `semantic-release`.  See the section here for more details:

* https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#use-breaking-change-to-trigger-a-major-version-change

In terms of the content, I'm sure you could use pretty much what you've already provided in the section I've quoted.

**Comment by kiniou** [comment]
Hi @myii :wave: 

I've completely missed to read the CONTRIBUTING document and i would like to express my apologies. :sweat_smile: 

I'm actually using this change in my fork and i'm not in a hurry waiting for a proper review. :wink:

Plus, this PR can be a place to discuss if we can transform this breaking change into some opt-in feature flag or by using a deprecation path otherwise.

**Review by javierbertoli — APPROVED** [review]
Great addition, @kiniou, thanks!

As we're using semantic versioning, I'm perfectly OK with this PR changing the behavior (for good) of the formula and flag it.

**Review by myii — CHANGES_REQUESTED** [review]
Thanks for the review, @javierbertoli.

Just using this `Request changes` as a placeholder to remind ourselves that the `BREAKING CHANGE` message needs to be added to the commit message before this is merged.

**Comment by kiniou** [comment]
Hi @myii and @javierbertoli and thanks for the review 😊.

I took a shoot at adding a BREAKING CHANGE paragraph. I'm just not sure if it will work with this kind of formatting (i.e code block).

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
> I took a shoot at adding a BREAKING CHANGE paragraph. I'm just not sure if it will work with this kind of formatting (i.e code block).

Let's merge it and see...!  Thanks for the contribution, @kiniou!

**Comment by myii** [comment]
@kiniou The code block came through fine!

**Pull request merged**
