### PR TITLE
Reload after install, to enable salt.modules.acme.

### PR DESCRIPTION
**Pull request by OrangeDog**

### CODE REVIEW

**Comment by OrangeDog** [comment]
@myii I'd forgotten about this - can you take a look?

**Comment by myii** [comment]
@OrangeDog Sure.  Since @javierbertoli is the global code owner here, let's get an opinion from him first.  Would you mind rebasing to fix the conflict and the commit message in the meantime?  The proposal looks fine to me.

**Comment by javierbertoli** [comment]
@OrangeDog, @myii, it LGTM. I think we can merge it one it's rebased.

**Comment by myii** [comment]
Thanks for fixing that @OrangeDog, merged with an amended commit message for `semantic-release`:

```
fix(install): reload after install, to enable salt.modules.acme
```

**Pull request merged**
